// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS17_Wfk0v-en96L5SbHtT4iM9v5TWWAE',
    appId: '1:874731895290:web:56770ed6813237af514c43',
    messagingSenderId: '874731895290',
    projectId: 'prolean-ai',
    authDomain: 'prolean-ai.firebaseapp.com',
    storageBucket: 'prolean-ai.firebasestorage.app',
    measurementId: 'G-QE8S1HCK5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI5xj0gPjW20i0QmISwAKx84k5SVYhhu0',
    appId: '1:392971587776:android:08235261a6854abdb9dd25',
    messagingSenderId: '392971587776',
    projectId: 'prolearn-ai-micha',
    storageBucket: 'prolearn-ai-micha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDORzmqoGz26luiOzyFamMu8YyhF4IUGx8',
    appId: '1:392971587776:ios:cbee8b5b701d3cd8b9dd25',
    messagingSenderId: '392971587776',
    projectId: 'prolearn-ai-micha',
    storageBucket: 'prolearn-ai-micha.firebasestorage.app',
    iosBundleId: 'com.example.prolearnAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDORzmqoGz26luiOzyFamMu8YyhF4IUGx8',
    appId: '1:392971587776:ios:cbee8b5b701d3cd8b9dd25',
    messagingSenderId: '392971587776',
    projectId: 'prolearn-ai-micha',
    storageBucket: 'prolearn-ai-micha.firebasestorage.app',
    iosBundleId: 'com.example.prolearnAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS17_Wfk0v-en96L5SbHtT4iM9v5TWWAE',
    appId: '1:874731895290:web:56770ed6813237af514c43',
    messagingSenderId: '874731895290',
    projectId: 'prolean-ai',
    authDomain: 'prolean-ai.firebaseapp.com',
    storageBucket: 'prolean-ai.firebasestorage.app',
    measurementId: 'G-QE8S1HCK5N',
  );
}
